/*

*/

#ifndef AGGREGATOR_EXPORT_H_
#define AGGREGATOR_EXPORT_H_

#if defined(AGGREGATOR_IMPLEMENTATION)
#define AGGREGATOR_EXPORT               SYMBOL_EXPORT
#define AGGREGATOR_EXPORT_PRIVATE       SYMBOL_EXPORT
#else
#define AGGREGATOR_EXPORT
#define AGGREGATOR_EXPORT_PRIVATE
#endif  // defined(AGGREGATOR_IMPLEMENTATION)

#endif // AGGREGATOR_EXPORT_H_
